#
# Generated the prime numbers and generated used by SSH DH Group KEX.
#
name: GEN

# Only run on pull requests and only for Python files.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  generate:
    name: 'Size ${{ matrix.size }}'
    strategy:
      fail-fast: false
      matrix:
        # size: [ 1024, 1536, 2048, 3072, 4096, 6144, 8192]
        size: [ 1024, 1536, 2048]

    runs-on: ubuntu-latest
    steps:

    # Make sure we don't have multiple jobs
    - uses: chevah/auto-cancel-redundant-job@v1

    - name: Candidate
      run: |
        ssh-keygen -M generate -O bits=${{ matrix.size }} candidate-${{ matrix.size }}

    - name: Validate
      run: |
        ssh-keygen -M screen -f candidate-${{ matrix.size }} validated-${{ matrix.size }}

    - uses: actions/upload-artifact@v2
      with:
        name: moduli-${{ matrix.size }}
        path: validated-*

  agregate:
    needs: generate
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2

    - name: Debug
      run: ls
