#
# Generated the prime numbers and generated used by SSH DH Group KEX.
#
name: GEN

# Only run on pull requests and only for Python files.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:

  generate:
    name: 'generate ${{ matrix.size }}'
    strategy:
      fail-fast: false
      matrix:
        # size: [ 1024, 1536, 2048, 3072, 4096, 6144, 7680, 8192]
        size: [ 1024, 1536, 2048, 4096, 6144, 7680, 8192]

    runs-on: ubuntu-latest
    steps:

    # Make sure we don't have multiple jobs
    - uses: chevah/auto-cancel-redundant-job@v1

    - name: Candidate
      run: |
        ssh-keygen -M generate -O bits=${{ matrix.size }} candidate-${{ matrix.size }}

    - name: Validate
      run: |
        ssh-keygen -M screen -f candidate-${{ matrix.size }} validated-${{ matrix.size }}

    - uses: actions/upload-artifact@v2
      with:
        name: partial
        path: validated-*

  combine:
    needs: generate
    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2

    - name: Debug
      run: ls -al *

    - name: OpenSSH /etc/ssh/moduli
      run: cat validated-* > etc_ssh_moduli

    - name: Chevah Python Dict
      run: python chevah_format.py validated- chevah_moduli.py

    - uses: actions/upload-artifact@v2
      with:
        name: result
        path: |
          etc_ssh_moduli
          chevah_moduli.py
