#
# Generated the prime numbers and generated used by SSH DH Group KEX.
#
# Generating is fast. Max 15 minutes.
# Validating is slow. 30 hours.
#
# Since the GitHub VM have 2 CPU each job will run 2 validating tasks.
# A job can run for 6 hours... so 12 hours of validation time per job.
# With 3 jobs for a certain size we should do it.
#
# It generates primes for 1024, 1536, 2048, 3072, 4096, 6144, 7680, 8192
#
name: CD

# Only run on pull requests and only for Python files.
on:
  # Pull requests are enabled for development.
  pull_request:
    branches: [ main ]

  # https://crontab.guru
  schedule:
    # At 02:00 on Saturday
    - cron: '0 2 * * 6'

jobs:

  prevent_duplicates:
    runs-on: ubuntu-latest
    steps:
    - uses: chevah/auto-cancel-redundant-job@v1
    - uses: chevah/python-info-action@v1


  generate:
    name: 'generate ${{ matrix.size }}'
    needs: prevent_duplicates
    strategy:
      matrix:
        size: [ 1024, 1536,  2048, 3072, 4096 ]
        split: [2]
        include:
          - size: 6144
            split: 4
          - size: 7680
            split: 12
          - size: 8192
            split: 24


    runs-on: ubuntu-latest
    steps:

    - name: Candidate
      run: |

        ssh-keygen -M generate -O bits=${{ matrix.size }} full.1 &
        PID1=$!
        ssh-keygen -M generate -O bits=${{ matrix.size }} full.2 &
        PID2=$!

        # After getting the PID of each run wait for both
        # and record any failure signaled via a non-zero exit code.
        FAIL=0
        wait $PID1 || let "FAIL+=1"
        wait $PID2 || let "FAIL+=1"

        cat full.2 >> full.1

        # Split as screening a single file on GitHub can't take more than
        # 6 hours.
        # We split with 2 digits as 7680 requires 12 chunks.
        # Split as round-robin as it looks like the first batch alwasy
        # takes longer to validate.
        split -d -a 2 -n r/${{ matrix.split }} full.1 g-${{ matrix.size }}.

        exit $FAIL

    - uses: actions/upload-artifact@v2
      with:
        name: candidate-${{ matrix.size }}
        path: g-*
        retention-days: 1


  screen:
    needs: generate
    name: 'screen ${{ matrix.size }}'
    strategy:
      matrix:
        size: [ 1024, 1536, 2048, 3072, 4096 ]
        split: [2]
        start: [0]

        # For big primes it can take 30 hours on a single CPU.
        include:
          - size: 6144
            split: 4
            start: 0
          - size: 6144
            split: 4
            start: 2

          - size: 7680
            split: 12
            start: 0
          - size: 7680
            split: 12
            start: 2
          - size: 7680
            split: 12
            start: 4
          - size: 7680
            split: 12
            start: 6
          - size: 7680
            split: 12
            start: 8
          - size: 7680
            split: 12
            start: 10

          - size: 8192
            split: 24
            start: 0
          - size: 8192
            split: 24
            start: 2
          - size: 8192
            split: 24
            start: 4
          - size: 8192
            split: 24
            start: 6
          - size: 8192
            split: 24
            start: 8
          - size: 8192
            split: 24
            start: 10
          - size: 8192
            split: 24
            start: 12
          - size: 8192
            split: 24
            start: 14
          - size: 8192
            split: 24
            start: 16
          - size: 8192
            split: 24
            start: 18
          - size: 8192
            split: 24
            start: 20
          - size: 8192
            split: 24
            start: 22

    runs-on: ubuntu-latest
    steps:

    - uses: actions/download-artifact@v2
      with:
        name: candidate-${{ matrix.size }}

    - name: Validate
      run: |
        # Prepare all input as shell variables.
        size=${{ matrix.size }}
        first_index=${{ matrix.start }}
        second_index=$(( $first_index + 1 ))
        first_index=`printf %02d $first_index`
        second_index=`printf %02d $second_index`
        # Some debugging.
        ls -al *
        declare -p

        # The action.
        ssh-keygen -M screen -f g-$size.$first_index  v-$size-$first_index &
        PID1=$!
        ssh-keygen -M screen -f g-$size.$second_index  v-$size-$second_index &
        PID2=$!

        FAIL=0
        wait $PID1 || let "FAIL+=1"
        wait $PID2 || let "FAIL+=1"
        exit $FAIL

    - uses: actions/upload-artifact@v2
      with:
        name: validated
        path: v-*
        retention-days: 1


  combine:
    needs: screen
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: validated

    - name: Debug
      run: |
        ls -al *
        wc -l v-*

    - name: OpenSSH /etc/ssh/moduli
      run: |
        now=`date -Iminutes`
        echo "# https://github.com/chevah/ssh-moduli/ $now" > etc_ssh_moduli
        echo "# Time Type Tests Tries Size Generator Modulus" >> etc_ssh_moduli

        cat v-* | sort -u >> etc_ssh_moduli

    - name: Chevah Python Dict
      run: python chevah_format.py etc_ssh_moduli chevah_moduli.py

    # Clean all previous artifact to reduce the noise on the artifacts page.
    - uses: chevah/delete-artifact@1-glob-support
      with:
        name: '**'
        useGlob: true

    - uses: actions/upload-artifact@v2
      with:
        name: etc_ssh_moduli
        path: |
          etc_ssh_moduli

    - uses: actions/upload-artifact@v2
      with:
        name: chevah_moduli
        path: |
          chevah_moduli.py

    - name: Artifacts link
      run: |
        echo ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}#artifacts
